name: Notificador Automático de Eventos
on:
  schedule:
    - cron: '*/15 * * * *' # ⏱️ Revisa cada 15 minutos
  workflow_dispatch: # 👈 Botón manual en GitHub por si quieres forzarla

jobs:
  check-events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Ejecutar Notificador

      # 🔥 AQUÍ INYECTAMOS EL SECRETO HACIA TU SCRIPT 🔥
        env:
          ONESIGNAL_KEY: ${{ secrets.ONESIGNAL_KEY }}


        run: node scripts/notificador.js

      - name: Guardar Historial
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add scripts/notificados.json
          git commit -m "chore: actualiza historial notificaciones" || exit 0
          git push